name: file_picker_cross
description: Select, open, choose or pick documents, images videos or other files on Android, iOS, the desktop and the web for reading, writing, use as String, byte list or HTTP uploads.
version: 5.0.0
homepage: https://gitlab.com/TheOneWithTheBraid/file_picker_cross
repository: https://gitlab.com/TheOneWithTheBraid/file_picker_cross.git
issue_tracker: https://gitlab.com/TheOneWithTheBraid/file_picker_cross/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  file_picker: ^6.0.0
  http: ^1.1.0
  http_parser: ^4.0.0
  file_selector: ^0.8.2
  file_selector_linux: ^0.0.2
  flutter_file_dialog: ^2.3.0
  path_provider: ^2.1.1
  package_info_plus: ^4.2.0
  share_plus: ^4.0.4
  disk_space: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4
  import_sorter: ^4.6.0
  test: ^1.19.5
